import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RAMDOM NAME DRAWER",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col">
          <main className="flex-grow">{children}</main>

          <footer className="bg-gray-100 text-gray-600 text-sm text-center py-4 border-t">
            <p>
              © {new Date().getFullYear()} Developed by{" "}
              <a
                href="https://thanh-loi-dev.netlify.app/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-600 hover:underline"
              >
                tloidev
              </a>
              . All rights reserved.
              <br />
              <span className="text-xs text-gray-400">version: 1.2.0</span>
            </p>
          </footer>
        </div>
      </body>
    </html>
  );
}
